apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-result-app-deploy
  labels:
    name: voting-result-app-deploy
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-result-app-pod
      app: voting-app
  template:
    metadata:
      name: voting-result-app-pod
      labels:
        name: voting-result-app-pod
        app: voting-app
    spec:
      containers:
        - name: voting-result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80