apiVersion: v1
kind: Service
metadata:
  name: voting-result-app-service
  labels:
    name: voting-result-app-service
    app: voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: voting-result-app-pod
    app: voting-app
