
apiVersion: v1
kind: Service
metadata:
  name: catalog-api-service
  labels:
    app: catalog-api
    tenant: tga
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    app: catalog-api
