apiVersion: v1
kind: Pod
metadata:
  name: ecom-api
  labels:
    app: catalog-api
    tenant: tga
spec:
  containers:
    - name: product-catalog-api
      image: nginx
      env:
        - name: ASP
